name: Azure Continuous Delivery - Bun App (no tests)

on:
  workflow_dispatch:
    inputs:
      IMAGE_REPOSITORY:
        description: 'Repository of the image (same as declared in App Service creation)'
        required: true
        default: 'api-pds006'
      IMAGE_TAG:
        description: 'Tag of the image'
        required: true
        default: 'latest'
      AZURE_WEBAPP_NAME:
        description: 'Nombre del App Service en Azure'
        required: true
        default: 'pds006'
      PORT:
        description: 'Port of the application (container)'
        required: true
        default: '3000'

env:
  # Datos del container registry
  ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME_NICOLAS }}.azurecr.io
  IMAGE_FULL: ${{ secrets.ACR_NAME_NICOLAS }}.azurecr.io/${{ github.event.inputs.IMAGE_REPOSITORY }}:${{ github.event.inputs.IMAGE_TAG }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push Docker image to ACR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_NAME_NICOLAS }}
          password: ${{ secrets.ACR_PASSWORD_NICOLAS }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_FULL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    name: Deploy image to Azure Web App (container)
    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_NICOLAS }}
          images: ${{ env.IMAGE_FULL }}
